import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import NextAuthProvider from "@/providers/SessionProvider";
import AuthButton from "@/components/AuthButton";


import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-50 text-slate-900">
        <NextAuthProvider>
          <header className="border-b bg-white">
            <nav className="mx-auto max-w-5xl px-4 py-3 flex items-center gap-4">
              <Link href="/" className="font-semibold">VulnTracker</Link>
              <Link href="/add" className="text-sm underline">Add</Link>
              <a href="/api/export.csv" className="text-sm underline">Export CSV</a>
              <AuthButton />
            </nav>
          </header>
          <main className="mx-auto max-w-5xl px-4 py-6">{children}</main>
          <Toaster position="top-right" />
        </NextAuthProvider>
      </body>
    </html>
  );
}

